# Generated by Django 2.0.3 on 2019-07-02 21:41

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Addons',
            new_name='Addon',
        ),
    ]
