# Generated by Django 2.0.3 on 2019-07-03 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20190702_1741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addon',
            old_name='addonName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='addon',
            old_name='addonPrice',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='pasta',
            old_name='pastaName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='pizza',
            old_name='pizzaName',
            new_name='itemType',
        ),
        migrations.RenameField(
            model_name='pizza',
            old_name='pizzaType',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='platter',
            old_name='platterName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='salad',
            old_name='saladName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='sub',
            old_name='subName',
            new_name='name',
        ),
    ]
