# Generated by Django 2.0.3 on 2019-07-03 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20190702_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalorder',
            name='orderStatus',
            field=models.CharField(default='Completed', max_length=20),
            preserve_default=False,
        ),
    ]
